# Generated by Django 5.2.1 on 2025-08-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250826_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
