# Generated by Django 4.2.7 on 2025-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('clicks', models.PositiveIntegerField()),
                ('sales', models.PositiveIntegerField()),
                ('click_sales_ratio', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_per_click', models.FloatField()),
            ],
        ),
    ]
